
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.elsevier.opsbank2.inputservice.v1;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-11-01T17:42:24.139+05:30
 * Generated source version: 3.4.5
 *
 */

@javax.jws.WebService(
                      serviceName = "InputService",
                      portName = "InputServiceSOAP",
                      targetNamespace = "http://www.elsevier.com/opsbank2/inputservice/v1",
                      wsdlLocation = "https://input-soap-service-ob2uat.apps.ose-nonprod.cp.tio.systems/cxf/ob2/inputService/?wsdl",
                      endpointInterface = "com.elsevier.opsbank2.inputservice.v1.InputService")

public class InputServiceSOAPImpl implements InputService {

    private static final Logger LOG = Logger.getLogger(InputServiceSOAPImpl.class.getName());

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.inputservice.v1.InputService#submitValidateInputDelivery(com.elsevier.opsbank2.input.v1.OPSBankInput parameters)*
     */
    public com.elsevier.opsbank2.inputservice.v1.ValidateInputDeliveryResponse submitValidateInputDelivery(com.elsevier.opsbank2.input.v1.OPSBankInput parameters) {
        LOG.info("Executing operation submitValidateInputDelivery");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.inputservice.v1.ValidateInputDeliveryResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.inputservice.v1.InputService#submitGenerateInputFiles(com.elsevier.opsbank2.input.v1.OPSBankInput parameters)*
     */
    public com.elsevier.opsbank2.inputservice.v1.GenerateInputFilesResponse submitGenerateInputFiles(com.elsevier.opsbank2.input.v1.OPSBankInput parameters) {
        LOG.info("Executing operation submitGenerateInputFiles");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.inputservice.v1.GenerateInputFilesResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.inputservice.v1.InputService#submitRetrieveTPAAndPublisher(com.elsevier.opsbank2.input.v1.RetrieveTPAAndPublisher parameters)*
     */
    public com.elsevier.opsbank2.inputservice.v1.RetrieveTPAAndPublisherResponse submitRetrieveTPAAndPublisher(com.elsevier.opsbank2.input.v1.RetrieveTPAAndPublisher parameters) {
        LOG.info("Executing operation submitRetrieveTPAAndPublisher");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.inputservice.v1.RetrieveTPAAndPublisherResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.inputservice.v1.InputService#submitPatentDetailsRetrieval(com.elsevier.opsbank2.input.v1.PatentDetailsRetrievalRequest parameters)*
     */
    public com.elsevier.opsbank2.inputservice.v1.PatentDetailsRetrievalResponse submitPatentDetailsRetrieval(com.elsevier.opsbank2.input.v1.PatentDetailsRetrievalRequest parameters) {
        LOG.info("Executing operation submitPatentDetailsRetrieval");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.inputservice.v1.PatentDetailsRetrievalResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.inputservice.v1.InputService#submitEmitExhibitEvents(com.elsevier.opsbank2.input.v1.ExportCARFileInfo parameters)*
     */
    public com.elsevier.opsbank2.inputservice.v1.EmitExhibitEventsResponse submitEmitExhibitEvents(com.elsevier.opsbank2.input.v1.ExportCARFileInfo parameters) {
        LOG.info("Executing operation submitEmitExhibitEvents");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.inputservice.v1.EmitExhibitEventsResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.inputservice.v1.InputService#submitSimulateCARDelivery(com.elsevier.opsbank2.input.v1.OPSBankInput parameters)*
     */
    public com.elsevier.opsbank2.inputservice.v1.SimulateCARDeliveryResponse submitSimulateCARDelivery(com.elsevier.opsbank2.input.v1.OPSBankInput parameters) {
        LOG.info("Executing operation submitSimulateCARDelivery");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.inputservice.v1.SimulateCARDeliveryResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.inputservice.v1.InputService#submitStopPatentProcessing(com.elsevier.opsbank2.input.v1.StopPatentProcessing parameters)*
     */
    public com.elsevier.opsbank2.inputservice.v1.StopPatentProcessingResponse submitStopPatentProcessing(com.elsevier.opsbank2.input.v1.StopPatentProcessing parameters) {
        LOG.info("Executing operation submitStopPatentProcessing");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.inputservice.v1.StopPatentProcessingResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.inputservice.v1.InputService#submitTransformExportedCAR(com.elsevier.opsbank2.input.v1.ExportCARFileInfo parameters)*
     */
    public com.elsevier.opsbank2.inputservice.v1.TransformExportedCARResponse submitTransformExportedCAR(com.elsevier.opsbank2.input.v1.ExportCARFileInfo parameters) {
        LOG.info("Executing operation submitTransformExportedCAR");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.inputservice.v1.TransformExportedCARResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.inputservice.v1.InputService#submitCloseInputOrder(com.elsevier.opsbank2.input.v1.OPSBankInput parameters)*
     */
    public com.elsevier.opsbank2.inputservice.v1.CloseInputOrderResponse submitCloseInputOrder(com.elsevier.opsbank2.input.v1.OPSBankInput parameters) {
        LOG.info("Executing operation submitCloseInputOrder");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.inputservice.v1.CloseInputOrderResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.inputservice.v1.InputService#submitCreateInputOrder(com.elsevier.opsbank2.input.v1.OPSBankInput parameters)*
     */
    public com.elsevier.opsbank2.inputservice.v1.CreateInputOrderResponse submitCreateInputOrder(com.elsevier.opsbank2.input.v1.OPSBankInput parameters) {
        LOG.info("Executing operation submitCreateInputOrder");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.inputservice.v1.CreateInputOrderResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.inputservice.v1.InputService#submitRegisterInputDelivery(com.elsevier.opsbank2.input.v1.OPSBankInput parameters)*
     */
    public com.elsevier.opsbank2.inputservice.v1.RegisterInputDeliveryResponse submitRegisterInputDelivery(com.elsevier.opsbank2.input.v1.OPSBankInput parameters) {
        LOG.info("Executing operation submitRegisterInputDelivery");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.inputservice.v1.RegisterInputDeliveryResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.inputservice.v1.InputService#submitProcessInputDelivery(com.elsevier.opsbank2.input.v1.OPSBankInput parameters)*
     */
    public com.elsevier.opsbank2.inputservice.v1.ProcessInputDeliveryResponse submitProcessInputDelivery(com.elsevier.opsbank2.input.v1.OPSBankInput parameters) {
        LOG.info("Executing operation submitProcessInputDelivery");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.inputservice.v1.ProcessInputDeliveryResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.inputservice.v1.InputService#submitPatentFamilyProcessing(com.elsevier.opsbank2.input.v1.OPSBankInput parameters)*
     */
    public com.elsevier.opsbank2.inputservice.v1.PatentFamilyProcessingResponse submitPatentFamilyProcessing(com.elsevier.opsbank2.input.v1.OPSBankInput parameters) {
        LOG.info("Executing operation submitPatentFamilyProcessing");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.inputservice.v1.PatentFamilyProcessingResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.inputservice.v1.InputService#submitExportCAR(com.elsevier.opsbank2.input.v1.ExportCARFileInfo parameters)*
     */
    public com.elsevier.opsbank2.inputservice.v1.ExportCARResponse submitExportCAR(com.elsevier.opsbank2.input.v1.ExportCARFileInfo parameters) {
        LOG.info("Executing operation submitExportCAR");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.inputservice.v1.ExportCARResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.inputservice.v1.InputService#submitMatchPatentFamilyProcessing(com.elsevier.opsbank2.input.v1.MatchPatentFamily parameters)*
     */
    public com.elsevier.opsbank2.inputservice.v1.MatchPatentFamilyProcessingResponse submitMatchPatentFamilyProcessing(com.elsevier.opsbank2.input.v1.MatchPatentFamily parameters) {
        LOG.info("Executing operation submitMatchPatentFamilyProcessing");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.inputservice.v1.MatchPatentFamilyProcessingResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.inputservice.v1.InputService#submitInputOrderCARIdsRetrieval(com.elsevier.opsbank2.input.v1.InputOrderCARIdsRetrievalRequest parameters)*
     */
    public com.elsevier.opsbank2.inputservice.v1.InputOrderCARIdsRetrievalResponse submitInputOrderCARIdsRetrieval(com.elsevier.opsbank2.input.v1.InputOrderCARIdsRetrievalRequest parameters) {
        LOG.info("Executing operation submitInputOrderCARIdsRetrieval");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.inputservice.v1.InputOrderCARIdsRetrievalResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.inputservice.v1.InputService#submitDecideNextActivity(com.elsevier.opsbank2.input.v1.OPSBankInput parameters)*
     */
    public com.elsevier.opsbank2.inputservice.v1.DecideNextActivityResponse submitDecideNextActivity(com.elsevier.opsbank2.input.v1.OPSBankInput parameters) {
        LOG.info("Executing operation submitDecideNextActivity");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.inputservice.v1.DecideNextActivityResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.inputservice.v1.InputService#submitUploadInputOrder(com.elsevier.opsbank2.input.v1.OPSBankInput parameters)*
     */
    public com.elsevier.opsbank2.inputservice.v1.UploadInputOrderResponse submitUploadInputOrder(com.elsevier.opsbank2.input.v1.OPSBankInput parameters) {
        LOG.info("Executing operation submitUploadInputOrder");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.inputservice.v1.UploadInputOrderResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.inputservice.v1.InputService#submitPatentCARInformation(com.elsevier.opsbank2.input.v1.OPSBankInput parameters)*
     */
    public com.elsevier.opsbank2.inputservice.v1.PatentCARInformationResponse submitPatentCARInformation(com.elsevier.opsbank2.input.v1.OPSBankInput parameters) {
        LOG.info("Executing operation submitPatentCARInformation");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.inputservice.v1.PatentCARInformationResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
