package com.elsevier.opsbank2.inputservice.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-11-01T17:42:24.209+05:30
 * Generated source version: 3.4.5
 *
 */
@WebServiceClient(name = "InputService",
                  wsdlLocation = "https://input-soap-service-ob2uat.apps.ose-nonprod.cp.tio.systems/cxf/ob2/inputService/?wsdl",
                  targetNamespace = "http://www.elsevier.com/opsbank2/inputservice/v1")
public class InputService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.elsevier.com/opsbank2/inputservice/v1", "InputService");
    public final static QName InputServiceSOAP = new QName("http://www.elsevier.com/opsbank2/inputservice/v1", "InputServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("https://input-soap-service-ob2uat.apps.ose-nonprod.cp.tio.systems/cxf/ob2/inputService/?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(InputService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://input-soap-service-ob2uat.apps.ose-nonprod.cp.tio.systems/cxf/ob2/inputService/?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public InputService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InputService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InputService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public InputService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public InputService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public InputService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns InputService
     */
    @WebEndpoint(name = "InputServiceSOAP")
    public InputService getInputServiceSOAP() {
        return super.getPort(InputServiceSOAP, InputService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InputService
     */
    @WebEndpoint(name = "InputServiceSOAP")
    public InputService getInputServiceSOAP(WebServiceFeature... features) {
        return super.getPort(InputServiceSOAP, InputService.class, features);
    }

}
