
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.elsevier.opsbank2.afterburner.v1;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-11-12T16:01:53.123+05:30
 * Generated source version: 3.4.5
 *
 */

@javax.jws.WebService(
                      serviceName = "AfterBurnerIntegrationService",
                      portName = "AfterBurnerIntegrationServiceSoap",
                      targetNamespace = "http://www.elsevier.com/opsbank2/afterburner/v1",
                      wsdlLocation = "https://output-soap-service-ob2uat.apps.ose-nonprod.cp.tio.systems/cxf/ob2/afterBurnerIntegService/?WSDL",
                      endpointInterface = "com.elsevier.opsbank2.afterburner.v1.AfterBurnerIntegrationService")

public class AfterBurnerIntegrationServiceSoapImpl implements AfterBurnerIntegrationService {

    private static final Logger LOG = Logger.getLogger(AfterBurnerIntegrationServiceSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.afterburner.v1.AfterBurnerIntegrationService#processAfterBurner(com.elsevier.opsbank2.afterburner.v1.ProcessAfterBurnerRequest parameters)*
     */
    public com.elsevier.opsbank2.afterburner.v1.ProcessAfterBurnerResponse processAfterBurner(ProcessAfterBurnerRequest parameters) {
        LOG.info("Executing operation processAfterBurner");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.afterburner.v1.ProcessAfterBurnerResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
