package com.elsevier.opsbank2.afterburner.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-11-12T16:01:53.164+05:30
 * Generated source version: 3.4.5
 *
 */
@WebService(targetNamespace = "http://www.elsevier.com/opsbank2/afterburner/v1", name = "AfterBurnerIntegrationService")
@XmlSeeAlso({ObjectFactory.class, com.elsevier.opsbank2.integration.common.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AfterBurnerIntegrationService {

    @WebMethod(action = "processAfterBurner")
    @WebResult(name = "processAfterBurnerResponse", targetNamespace = "http://www.elsevier.com/opsbank2/afterburner/v1", partName = "parameters")
    public ProcessAfterBurnerResponse processAfterBurner(

        @WebParam(partName = "parameters", name = "processAfterBurnerRequest", targetNamespace = "http://www.elsevier.com/opsbank2/afterburner/v1")
        ProcessAfterBurnerRequest parameters
    );
}
