
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.elsevier.opsbank2.outputorder.v1;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-11-12T15:51:31.634+05:30
 * Generated source version: 3.4.5
 *
 */

@javax.jws.WebService(
                      serviceName = "OutputOrderIntegrationService",
                      portName = "OutputOrderIntegrationServiceSoap",
                      targetNamespace = "http://www.elsevier.com/opsbank2/outputorder/v1",
                      wsdlLocation = "https://output-order-soap-proxy-service-ob2uat.apps.ose-nonprod.cp.tio.systems/ob2/outputOrderIntegService/?wsdl",
                      endpointInterface = "com.elsevier.opsbank2.outputorder.v1.OutputOrderIntegrationService")

public class OutputOrderIntegrationServiceSoapImpl implements OutputOrderIntegrationService {

    private static final Logger LOG = Logger.getLogger(OutputOrderIntegrationServiceSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.outputorder.v1.OutputOrderIntegrationService#updateOrderType(com.elsevier.opsbank2.outputorder.v1.UpdateOrderTypeRequest parameters)*
     */
    public com.elsevier.opsbank2.outputorder.v1.UpdateOrderTypeResponse updateOrderType(UpdateOrderTypeRequest parameters) {
        LOG.info("Executing operation updateOrderType");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.outputorder.v1.UpdateOrderTypeResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.outputorder.v1.OutputOrderIntegrationService#finaliseOutputOrder(com.elsevier.opsbank2.outputorder.v1.FinaliseOutputOrderRequest parameters)*
     */
    public com.elsevier.opsbank2.outputorder.v1.FinaliseOutputOrderResponse finaliseOutputOrder(FinaliseOutputOrderRequest parameters) {
        LOG.info("Executing operation finaliseOutputOrder");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.outputorder.v1.FinaliseOutputOrderResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.outputorder.v1.OutputOrderIntegrationService#updateOutputOrderStatus(com.elsevier.opsbank2.outputorder.v1.UpdateOutputOrderStatusRequest parameters)*
     */
    public com.elsevier.opsbank2.outputorder.v1.UpdateOutputOrderStatusResponse updateOutputOrderStatus(UpdateOutputOrderStatusRequest parameters) {
        LOG.info("Executing operation updateOutputOrderStatus");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.outputorder.v1.UpdateOutputOrderStatusResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.outputorder.v1.OutputOrderIntegrationService#createOutputOrderProcess(com.elsevier.opsbank2.outputorder.v1.CreateOutputOrderProcessRequest parameters)*
     */
    public com.elsevier.opsbank2.outputorder.v1.CreateOutputOrderProcessResponse createOutputOrderProcess(CreateOutputOrderProcessRequest parameters) {
        LOG.info("Executing operation createOutputOrderProcess");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.outputorder.v1.CreateOutputOrderProcessResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
