package com.elsevier.opsbank2.outputorder.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-11-12T15:51:31.702+05:30
 * Generated source version: 3.4.5
 *
 */
@WebServiceClient(name = "OutputOrderIntegrationService",
                  wsdlLocation = "https://output-order-soap-proxy-service-ob2uat.apps.ose-nonprod.cp.tio.systems/ob2/outputOrderIntegService/?wsdl",
                  targetNamespace = "http://www.elsevier.com/opsbank2/outputorder/v1")
public class OutputOrderIntegrationService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.elsevier.com/opsbank2/outputorder/v1", "OutputOrderIntegrationService");
    public final static QName OutputOrderIntegrationServiceSoap = new QName("http://www.elsevier.com/opsbank2/outputorder/v1", "OutputOrderIntegrationServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("https://output-order-soap-proxy-service-ob2uat.apps.ose-nonprod.cp.tio.systems/ob2/outputOrderIntegService/?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OutputOrderIntegrationService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://output-order-soap-proxy-service-ob2uat.apps.ose-nonprod.cp.tio.systems/ob2/outputOrderIntegService/?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OutputOrderIntegrationService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OutputOrderIntegrationService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OutputOrderIntegrationService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public OutputOrderIntegrationService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OutputOrderIntegrationService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OutputOrderIntegrationService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns OutputOrderIntegrationService
     */
    @WebEndpoint(name = "OutputOrderIntegrationServiceSoap")
    public OutputOrderIntegrationService getOutputOrderIntegrationServiceSoap() {
        return super.getPort(OutputOrderIntegrationServiceSoap, OutputOrderIntegrationService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OutputOrderIntegrationService
     */
    @WebEndpoint(name = "OutputOrderIntegrationServiceSoap")
    public OutputOrderIntegrationService getOutputOrderIntegrationServiceSoap(WebServiceFeature... features) {
        return super.getPort(OutputOrderIntegrationServiceSoap, OutputOrderIntegrationService.class, features);
    }

}
