package com.elsevier.opsbank2.outputorder.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-11-12T15:51:31.693+05:30
 * Generated source version: 3.4.5
 *
 */
@WebService(targetNamespace = "http://www.elsevier.com/opsbank2/outputorder/v1", name = "OutputOrderIntegrationService")
@XmlSeeAlso({com.elsevier.opsbank2.common.ObjectFactory.class, com.elsevier.opsbank2.integration.common.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OutputOrderIntegrationService {

    @WebMethod(action = "updateOrderType")
    @WebResult(name = "updateOrderTypeResponse", targetNamespace = "http://www.elsevier.com/opsbank2/outputorder/v1", partName = "parameters")
    public UpdateOrderTypeResponse updateOrderType(

        @WebParam(partName = "parameters", name = "updateOrderTypeRequest", targetNamespace = "http://www.elsevier.com/opsbank2/outputorder/v1")
        UpdateOrderTypeRequest parameters
    );

    @WebMethod(action = "finaliseOutputOrder")
    @WebResult(name = "finaliseOutputOrderResponse", targetNamespace = "http://www.elsevier.com/opsbank2/outputorder/v1", partName = "parameters")
    public FinaliseOutputOrderResponse finaliseOutputOrder(

        @WebParam(partName = "parameters", name = "finaliseOutputOrderRequest", targetNamespace = "http://www.elsevier.com/opsbank2/outputorder/v1")
        FinaliseOutputOrderRequest parameters
    );

    @WebMethod(action = "updateOutputOrderStatus")
    @WebResult(name = "updateOutputOrderStatusResponse", targetNamespace = "http://www.elsevier.com/opsbank2/outputorder/v1", partName = "parameters")
    public UpdateOutputOrderStatusResponse updateOutputOrderStatus(

        @WebParam(partName = "parameters", name = "updateOutputOrderStatusRequest", targetNamespace = "http://www.elsevier.com/opsbank2/outputorder/v1")
        UpdateOutputOrderStatusRequest parameters
    );

    @WebMethod(action = "createOutputOrderProcess")
    @WebResult(name = "createOutputOrderProcessResponse", targetNamespace = "http://www.elsevier.com/opsbank2/outputorder/v1", partName = "parameters")
    public CreateOutputOrderProcessResponse createOutputOrderProcess(

        @WebParam(partName = "parameters", name = "createOutputOrderProcessRequest", targetNamespace = "http://www.elsevier.com/opsbank2/outputorder/v1")
        CreateOutputOrderProcessRequest parameters
    );
}
