package com.elsevier.opsbank2.output.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2022-01-05T11:17:08.047+05:30
 * Generated source version: 3.4.5
 *
 */
@WebServiceClient(name = "OutputProcess",
                  wsdlLocation = "https://output-soap-service-ob2uat.apps.ose-nonprod.cp.tio.systems/cxf/ob2/outputDeliveryService/?wsdl",
                  targetNamespace = "http://www.elsevier.com/opsbank2/output/v1")
public class OutputProcess_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.elsevier.com/opsbank2/output/v1", "OutputProcess");
    public final static QName OutputProcessSOAP = new QName("http://www.elsevier.com/opsbank2/output/v1", "OutputProcessSOAP");
    static {
        URL url = null;
        try {
            url = new URL("https://output-soap-service-ob2uat.apps.ose-nonprod.cp.tio.systems/cxf/ob2/outputDeliveryService/?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OutputProcess_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://output-soap-service-ob2uat.apps.ose-nonprod.cp.tio.systems/cxf/ob2/outputDeliveryService/?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OutputProcess_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OutputProcess_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OutputProcess_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public OutputProcess_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OutputProcess_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OutputProcess_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns OutputProcess
     */
    @WebEndpoint(name = "OutputProcessSOAP")
    public OutputProcess getOutputProcessSOAP() {
        return super.getPort(OutputProcessSOAP, OutputProcess.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OutputProcess
     */
    @WebEndpoint(name = "OutputProcessSOAP")
    public OutputProcess getOutputProcessSOAP(WebServiceFeature... features) {
        return super.getPort(OutputProcessSOAP, OutputProcess.class, features);
    }

}
