
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.elsevier.opsbank2.output.v1;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2022-01-05T11:17:07.981+05:30
 * Generated source version: 3.4.5
 *
 */

@javax.jws.WebService(
                      serviceName = "OutputProcess",
                      portName = "OutputProcessSOAP",
                      targetNamespace = "http://www.elsevier.com/opsbank2/output/v1",
                      wsdlLocation = "https://output-soap-service-ob2uat.apps.ose-nonprod.cp.tio.systems/cxf/ob2/outputDeliveryService/?wsdl",
                      endpointInterface = "com.elsevier.opsbank2.output.v1.OutputProcess")

public class OutputProcessSOAPImpl implements OutputProcess {

    private static final Logger LOG = Logger.getLogger(OutputProcessSOAPImpl.class.getName());

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.output.v1.OutputProcess#submitGetUserDetails(com.elsevier.opsbank2.output.v1.GetUserDetailsRequest parameters)*
     */
    public com.elsevier.opsbank2.output.v1.GetUserDetailsResponse submitGetUserDetails(GetUserDetailsRequest parameters) {
        LOG.info("Executing operation submitGetUserDetails");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.output.v1.GetUserDetailsResponse _return = new com.elsevier.opsbank2.output.v1.GetUserDetailsResponse();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.output.v1.OutputProcess#registerDataDelivery(com.elsevier.opsbank2.output.v1.RegisterDataDeliveryRequest parameters)*
     */
    public com.elsevier.opsbank2.output.v1.RegisterDataDeliveryResponse registerDataDelivery(RegisterDataDeliveryRequest parameters) {
        LOG.info("Executing operation registerDataDelivery");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.output.v1.RegisterDataDeliveryResponse _return = new com.elsevier.opsbank2.output.v1.RegisterDataDeliveryResponse();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.output.v1.OutputProcess#submitStartOutputXMLGeneration(com.elsevier.opsbank2.output.v1.StartOutputXMLGenerationRequest parameters)*
     */
    public com.elsevier.opsbank2.output.v1.StartOutputXMLGenerationResponse submitStartOutputXMLGeneration(StartOutputXMLGenerationRequest parameters) {
        LOG.info("Executing operation submitStartOutputXMLGeneration");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.output.v1.StartOutputXMLGenerationResponse _return = new com.elsevier.opsbank2.output.v1.StartOutputXMLGenerationResponse();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.output.v1.OutputProcess#submitGetPostProcessStatus(com.elsevier.opsbank2.output.v1.GetPostProcessStatusRequest parameters)*
     */
    public com.elsevier.opsbank2.output.v1.GetPostProcessStatusResponse submitGetPostProcessStatus(GetPostProcessStatusRequest parameters) {
        LOG.info("Executing operation submitGetPostProcessStatus");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.output.v1.GetPostProcessStatusResponse _return = new com.elsevier.opsbank2.output.v1.GetPostProcessStatusResponse();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.output.v1.OutputProcess#submitGetUserAndOrderInfo(com.elsevier.opsbank2.output.v1.GetUserAndOrderInfoRequest parameters)*
     */
    public com.elsevier.opsbank2.output.v1.GetUserAndOrderInfoResponse submitGetUserAndOrderInfo(GetUserAndOrderInfoRequest parameters) {
        LOG.info("Executing operation submitGetUserAndOrderInfo");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.output.v1.GetUserAndOrderInfoResponse _return = new com.elsevier.opsbank2.output.v1.GetUserAndOrderInfoResponse();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.output.v1.OutputProcess#submitCancelDataDelivery(com.elsevier.opsbank2.output.v1.CancelDataDeliveryRequest parameters)*
     */
    public com.elsevier.opsbank2.output.v1.CancelDataDeliveryResponse submitCancelDataDelivery(CancelDataDeliveryRequest parameters) {
        LOG.info("Executing operation submitCancelDataDelivery");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.output.v1.CancelDataDeliveryResponse _return = new com.elsevier.opsbank2.output.v1.CancelDataDeliveryResponse();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.output.v1.OutputProcess#submitRunSearchProfile(com.elsevier.opsbank2.output.v1.RunSearchProfileRequest parameters)*
     */
    public com.elsevier.opsbank2.output.v1.RunSearchProfileResponse submitRunSearchProfile(RunSearchProfileRequest parameters) {
        LOG.info("Executing operation submitRunSearchProfile");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.output.v1.RunSearchProfileResponse _return = new com.elsevier.opsbank2.output.v1.RunSearchProfileResponse();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.output.v1.OutputProcess#submitDeliverOutputOrderDataFilesToCustomer(com.elsevier.opsbank2.output.v1.DeliverOutputOrderDataFilesToCustomerRequest parameters)*
     */
    public com.elsevier.opsbank2.output.v1.DeliverOutputOrderDataFilesToCustomerResponse submitDeliverOutputOrderDataFilesToCustomer(DeliverOutputOrderDataFilesToCustomerRequest parameters) {
        LOG.info("Executing operation submitDeliverOutputOrderDataFilesToCustomer");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.output.v1.DeliverOutputOrderDataFilesToCustomerResponse _return = new com.elsevier.opsbank2.output.v1.DeliverOutputOrderDataFilesToCustomerResponse();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.output.v1.OutputProcess#submitSendDeliveryNotificationEmail(com.elsevier.opsbank2.output.v1.SendDeliveryNotificationEmailRequest parameters)*
     */
    public com.elsevier.opsbank2.output.v1.SendDeliveryNotificationEmailResponse submitSendDeliveryNotificationEmail(SendDeliveryNotificationEmailRequest parameters) {
        LOG.info("Executing operation submitSendDeliveryNotificationEmail");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.output.v1.SendDeliveryNotificationEmailResponse _return = new com.elsevier.opsbank2.output.v1.SendDeliveryNotificationEmailResponse();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
