package com.elsevier.opsbank2.output.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2022-01-05T11:17:08.038+05:30
 * Generated source version: 3.4.5
 *
 */
@WebService(targetNamespace = "http://www.elsevier.com/opsbank2/output/v1", name = "OutputProcess")
@XmlSeeAlso({com.elsevier.obii.eis.service.ObjectFactory.class, org.apache.xml.xml_soap.ObjectFactory.class, com.elsevier.obii.vo.ObjectFactory.class, com.elsevier.obii.services.admin.vo.ObjectFactory.class, com.elsevier.obii.services.common.vo.ObjectFactory.class, opsbankiioutputlibrary.ObjectFactory.class, ObjectFactory.class, org.xmlsoap.schemas.soap.envelope.ObjectFactory.class, com.elsevier.obii.services.utility.vo.ObjectFactory.class, com.elsevier.obii.services.query.vo.ObjectFactory.class, com.elsevier.obii.services.utility.facade.ObjectFactory.class, com.elsevier.obii.eis.service.vo.ObjectFactory.class, com.elsevier.obii.services.outputorder.vo.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OutputProcess {

    @WebMethod(operationName = "SubmitGetUserDetails", action = "getUserDetails")
    @WebResult(name = "getUserDetailsResponse", targetNamespace = "http://www.elsevier.com/opsbank2/output/v1", partName = "parameters")
    public GetUserDetailsResponse submitGetUserDetails(

        @WebParam(partName = "parameters", name = "getUserDetailsRequest", targetNamespace = "http://www.elsevier.com/opsbank2/output/v1")
        GetUserDetailsRequest parameters
    );

    @WebMethod(operationName = "RegisterDataDelivery", action = "registerDataDelivery")
    @WebResult(name = "registerDataDeliveryResponse", targetNamespace = "http://www.elsevier.com/opsbank2/output/v1", partName = "parameters")
    public RegisterDataDeliveryResponse registerDataDelivery(

        @WebParam(partName = "parameters", name = "registerDataDeliveryRequest", targetNamespace = "http://www.elsevier.com/opsbank2/output/v1")
        RegisterDataDeliveryRequest parameters
    );

    @WebMethod(operationName = "SubmitStartOutputXMLGeneration", action = "startOutputXMLGeneration")
    @WebResult(name = "startOutputXMLGenerationResponse", targetNamespace = "http://www.elsevier.com/opsbank2/output/v1", partName = "parameters")
    public StartOutputXMLGenerationResponse submitStartOutputXMLGeneration(

        @WebParam(partName = "parameters", name = "startOutputXMLGenerationRequest", targetNamespace = "http://www.elsevier.com/opsbank2/output/v1")
        StartOutputXMLGenerationRequest parameters
    );

    @WebMethod(operationName = "SubmitGetPostProcessStatus", action = "getPostProcessStatus")
    @WebResult(name = "getPostProcessStatusResponse", targetNamespace = "http://www.elsevier.com/opsbank2/output/v1", partName = "parameters")
    public GetPostProcessStatusResponse submitGetPostProcessStatus(

        @WebParam(partName = "parameters", name = "getPostProcessStatusRequest", targetNamespace = "http://www.elsevier.com/opsbank2/output/v1")
        GetPostProcessStatusRequest parameters
    );

    @WebMethod(operationName = "SubmitGetUserAndOrderInfo", action = "getUserAndOrderInfo")
    @WebResult(name = "getUserAndOrderInfoResponse", targetNamespace = "http://www.elsevier.com/opsbank2/output/v1", partName = "parameters")
    public GetUserAndOrderInfoResponse submitGetUserAndOrderInfo(

        @WebParam(partName = "parameters", name = "getUserAndOrderInfoRequest", targetNamespace = "http://www.elsevier.com/opsbank2/output/v1")
        GetUserAndOrderInfoRequest parameters
    );

    @WebMethod(operationName = "SubmitCancelDataDelivery", action = "cancelDataDelivery")
    @WebResult(name = "cancelDataDeliveryResponse", targetNamespace = "http://www.elsevier.com/opsbank2/output/v1", partName = "parameters")
    public CancelDataDeliveryResponse submitCancelDataDelivery(

        @WebParam(partName = "parameters", name = "cancelDataDeliveryRequest", targetNamespace = "http://www.elsevier.com/opsbank2/output/v1")
        CancelDataDeliveryRequest parameters
    );

    @WebMethod(operationName = "SubmitRunSearchProfile", action = "runSearchProfile")
    @WebResult(name = "runSearchProfileResponse", targetNamespace = "http://www.elsevier.com/opsbank2/output/v1", partName = "parameters")
    public RunSearchProfileResponse submitRunSearchProfile(

        @WebParam(partName = "parameters", name = "runSearchProfileRequest", targetNamespace = "http://www.elsevier.com/opsbank2/output/v1")
        RunSearchProfileRequest parameters
    );

    @WebMethod(operationName = "SubmitDeliverOutputOrderDataFilesToCustomer", action = "deliverOutputOrderDataFilesToCustomer")
    @WebResult(name = "deliverOutputOrderDataFilesToCustomerResponse", targetNamespace = "http://www.elsevier.com/opsbank2/output/v1", partName = "parameters")
    public DeliverOutputOrderDataFilesToCustomerResponse submitDeliverOutputOrderDataFilesToCustomer(

        @WebParam(partName = "parameters", name = "deliverOutputOrderDataFilesToCustomerRequest", targetNamespace = "http://www.elsevier.com/opsbank2/output/v1")
        DeliverOutputOrderDataFilesToCustomerRequest parameters
    );

    @WebMethod(operationName = "SubmitSendDeliveryNotificationEmail", action = "sendDeliveryNotificationEmail")
    @WebResult(name = "sendDeliveryNotificationEmailResponse", targetNamespace = "http://www.elsevier.com/opsbank2/output/v1", partName = "parameters")
    public SendDeliveryNotificationEmailResponse submitSendDeliveryNotificationEmail(

        @WebParam(partName = "parameters", name = "sendDeliveryNotificationEmailRequest", targetNamespace = "http://www.elsevier.com/opsbank2/output/v1")
        SendDeliveryNotificationEmailRequest parameters
    );
}
