
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.elsevier.opsbank2.interfacerunservice.v1;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2022-01-11T14:06:58.063+05:30
 * Generated source version: 3.4.5
 *
 */

@javax.jws.WebService(
                      serviceName = "InterfaceRunService",
                      portName = "InterfaceRunServiceSOAP",
                      targetNamespace = "http://www.elsevier.com/opsbank2/interfacerunservice/v1",
                      wsdlLocation = "https://supporting-soap-service-ob2uat.apps.ose-nonprod.cp.tio.systems/cxf/ob2/interfaceRunService/?wsdl",
                      endpointInterface = "com.elsevier.opsbank2.interfacerunservice.v1.InterfaceRunService")

public class InterfaceRunServiceSOAPImpl implements InterfaceRunService {

    private static final Logger LOG = Logger.getLogger(InterfaceRunServiceSOAPImpl.class.getName());

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.interfacerunservice.v1.InterfaceRunService#submitRunInterface(com.elsevier.opsbank2.interfacerunservice.v1.RunInterface parameters)*
     */
    public com.elsevier.opsbank2.interfacerunservice.v1.RunInterfaceResponse submitRunInterface(RunInterface parameters) {
        LOG.info("Executing operation submitRunInterface");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.interfacerunservice.v1.RunInterfaceResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.elsevier.opsbank2.interfacerunservice.v1.InterfaceRunService#updateInterfaceRun(com.elsevier.opsbank2.interfacerunservice.v1.UpdateInterfaceRun parameters)*
     */
    public com.elsevier.opsbank2.interfacerunservice.v1.UpdateInterfaceRunResponse updateInterfaceRun(UpdateInterfaceRun parameters) {
        LOG.info("Executing operation updateInterfaceRun");
        System.out.println(parameters);
        try {
            com.elsevier.opsbank2.interfacerunservice.v1.UpdateInterfaceRunResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
